create database review;

create schema review;

create table review.review
(
    id            INTEGER PRIMARY KEY,
    description   varchar(1000) not null,
    grade         INTEGER       not null,
    user_id       INTEGER       not null,
    course_id     INTEGER       not null,
    is_updated    boolean       not null default false,
    creation_date DATE          not null default CURRENT_TIMESTAMP,
    update_date   DATE,
    is_banned     boolean                default false
);

create table review.review_mark
(
    id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    mark          INTEGER NOT NULL, -- -1 dislike 1 like
    user_id       INTEGER NOT NULL,
    review_id     INTEGER NOT NULL,
    creation_date DATE    not null default CURRENT_TIMESTAMP
);

create table review.review_ban
(
    id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admin_id      INTEGER       NOT NULL,
    review_id     INTEGER       NOT NULL,
    description   varchar(1000) not null,
    creation_date DATE          not null default CURRENT_TIMESTAMP
);